package view;

import java.io.File;
import javax.swing.ImageIcon;

public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        jRadioButton1.setText("Aguila");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        jRadioButton2.setText("Alce");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        jRadioButton3.setText("Caballo");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        jRadioButton4.setText("Cabra");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        jRadioButton5.setText("Gallo");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        jRadioButton6.setText("Tigre");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img paradigma/play.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lato Black", 3, 18)); // NOI18N
        jLabel2.setText("Descripción");

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("DejaVu Sans", 3, 18)); // NOI18N
        jRadioButton7.setText("Gato");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton1)
                                        .addComponent(jRadioButton5)
                                        .addComponent(jRadioButton4)
                                        .addComponent(jRadioButton3)
                                        .addComponent(jRadioButton2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButton6)
                                        .addGap(23, 23, 23)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton7)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(16, 16, 16)
                .addComponent(jRadioButton1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        //button aguila
        ImageIcon icono = new ImageIcon("/home/gonzalo/NetBeansProjects/appConMVC/agencia-de-viajes/ejercicioSonido/src/Img paradigma/aguila.jpg");
        jLabel1.setIcon(icono);
        String descripcion = "El Águila Real es considerada una de las especies de\n" +
"su género con mayor tamaño. La hembra es más \n" +
"grande que el macho. Mide entre 90 centímetros y \n" +
"un metro, con una envergadura de 2.15 a 2.27 m y \n" +
"peso de 3.8 a 6.6 kilogramos";
        jTextArea1.setText("");
       // descripcion
        jTextArea1.setText(descripcion);

        /*
        BasicPlayer sonido=new BasicPlayer();
        try {
            sonido.open(new File("/home/gonzalo/NetBeansProjects/appConMVC/agencia-de-viajes/ejercicio/src/audio/Cardenales De Nuevo León - Compré Una Cantina (Video Oficial).mp3"));
            sonido.play();
        } catch (Exception e) {
        }
        
         */
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // alce
        ImageIcon icono = new ImageIcon("/home/gonzalo/NetBeansProjects/appConMVC/agencia-de-viajes/ejercicioSonido/src/Img paradigma/alce.jpg");
        jLabel1.setIcon(icono);
         String descripcion ="Perteneciente a la familia de los cérvidos que incluye \n" +
"a los venados y a los renos– el alce es un mamífero\n" +
"artiodáctilo (con dedos pares en las patas) de gran\n" +
" tamaño: hasta tres metros de longitud, dos metros\n" +
"de altura y 500 kilos de peso.";
         jTextArea1.setText("");
         jTextArea1.setText(descripcion);
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // caballo
        ImageIcon icono = new ImageIcon("/home/gonzalo/NetBeansProjects/appConMVC/agencia-de-viajes/ejercicioSonido/src/Img paradigma/caballo.jpg");
        jLabel1.setIcon(icono);
        String descripcion ="Los caballos son animales mamíferos perisodáctilos\n" +
"en cuyas extremidades poseen dedos terminados \n" +
"en pezuñas que pertenecen a la familia de los \n" +
"équidos. Son herbívoros y el periodo de gestación \n" +
"de las hembras es de unos 11 meses, después del \n" +
"cual nace tan solo una cría.";
         jTextArea1.setText("");
         jTextArea1.setText(descripcion);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        //cabra
        ImageIcon icono = new ImageIcon("/home/gonzalo/NetBeansProjects/appConMVC/agencia-de-viajes/ejercicioSonido/src/Img paradigma/chivo.jpg");
        jLabel1.setIcon(icono);
        String descripcion =" Mamífero rumiante doméstico, como de un metro de \n" +
"altura , muy ágil para saltar y subir por lugares\n" +
"escarpados, con pelo corto, áspero y a menudo \n" +
"rojizo, cuernos vueltos hacia atrás, un mechón \n" +
"de pelos largos colgante de la mandíbula inferior \n" +
"y cola muy corta .";
         jTextArea1.setText("");
         jTextArea1.setText(descripcion);
        
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // gallo
        ImageIcon icono = new ImageIcon("/home/gonzalo/NetBeansProjects/appConMVC/agencia-de-viajes/ejercicioSonido/src/Img paradigma/gallo.jpg");
        jLabel1.setIcon(icono);
         String descripcion ="Ave doméstica del orden de las galliformes,con\n" +
"cresta roja y carnosa, pico corto, grueso y arqueado,\n" +
"de plumaje abundante, lustroso y a  menudo con \n" +
"visos irisados , cuyo macho tiene tarsos fuertes \n" +
"armados de espolones , y cuya hembra es de \n" +
"menor tamaño y tiene la cresta más pequeña.";
         jTextArea1.setText("");
         jTextArea1.setText(descripcion);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // tigre
        ImageIcon icono = new ImageIcon("/home/gonzalo/NetBeansProjects/appConMVC/agencia-de-viajes/ejercicioSonido/src/Img paradigma/tiger.jpg");
        jLabel1.setIcon(icono);
        String descripcion ="Tigre es el nombre común que reciben los integrantes\n" +
"de la especie Panthera tigris. Este animal mamífero, \n" +
"que está considerado  como el felino más grande del\n" +
"planeta, se caracteriza  por su pelaje amarillo con \n" +
"rayas negras en el lomo.";
         jTextArea1.setText("");
         jTextArea1.setText(descripcion);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        //gato
        ImageIcon icono = new ImageIcon("/home/gonzalo/NetBeansProjects/appConMVC/agencia-de-viajes/ejercicioSonido/src/Img paradigma/gato .jpg");
        jLabel1.setIcon(icono);
         String descripcion ="Mamífero de la familia de los félidos, digitígrado,   \n" +
"doméstico, de unos 50 cm de largo desde la cabeza\n" +
"hasta el arranque de la cola, que por sí sola mide \n" +
"unos 20 cm, de cabeza redonda, lengua muy áspera,\n" +
"patas cortas y generalmente pelaje suave y espeso, \n" +
"de color blanco, gris,pardo, rojizo o negro , \n" +
"empleado.";
         jTextArea1.setText("");
         jTextArea1.setText(descripcion);
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Basicplayer sonido = new Basicplayer();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
